BCMOHAD-25013: ETL route for Provincial Risk Tracking form.
bcgov/medis-etl-service pull request #139
Opened 2024-09-05 16:20 UTC by npham49

Description of changes:
- Added a new route to extract data from Provincial Risk Tracking form.

Instruction for testing:
- Add the following to application.properties:
```
pcd-provincial-risk-tracking-dir=pcd-provincial-risk-tracking

pcd.provincial.risk.tracking.username=
pcd.provincial.risk.tracking.password=
```

2024-09-09 21:53 UTC, weskubo-cgi requested changes

2024-09-10 15:38 UTC, npham49 commented on src/main/java/ca/bc/gov/chefs/etl/forms/pcd/provincialRiskTracking/processor/ProvincialRiskTrackingApiReponseProcessor.java
> +            ProvincialRiskTracking provincialRiskTracking = new ProvincialRiskTracking();
I switched to using modelMapper similar to StatusTracker.

2024-09-10 15:38 UTC, npham49 commented on src/main/java/ca/bc/gov/chefs/etl/forms/pcd/provincialRiskTracking/processor/ProvincialRiskTrackingApiReponseProcessor.java
> +		payload = JsonUtil.roundDigitsNumber(payload);
I think this was a result of copying, I have removed it!

2024-09-10 15:39 UTC, npham49 commented on src/main/java/ca/bc/gov/chefs/etl/forms/pcd/provincialRiskTracking/processor/ProvincialRiskTrackingApiProcessor.java
> +    	public ProvincialRiskTrackingApiProcessor() {
No clue why this is happening, my formatter thinks that the extra indentation is okay, so I manually fixed it; also enabled formatOnSave to catch these moving forward.

2024-09-10 16:25 UTC, weskubo-cgi commented on src/main/java/ca/bc/gov/chefs/etl/forms/pcd/provincialRiskTracking/processor/ProvincialRiskTrackingApiReponseProcessor.java
> +            ProvincialRiskTracking provincialRiskTracking = new ProvincialRiskTracking();
You don't need to define mappings unless they're nested or involved changes of names/types. It will infer the one to one mappings for you.

2024-09-10 18:30 UTC, weskubo-cgi approved these changes

2024-09-10 19:32 UTC, merged