BCMOHAD-25285: Fiscal Year Reporting Dates ETL
bcgov/medis-etl-service pull request #142
Opened 2024-10-28 04:54 UTC by npham49

Description of changes:
- Added ETL for Fiscal Year Reporting Dates.

2024-10-31 22:14 UTC, weskubo-cgi requested changes

2024-10-31 22:14 UTC, weskubo-cgi commented on src/main/java/ca/bc/gov/chefs/etl/forms/pcd/fiscalYearReportingDates/processor/PcdFiscalYearReportingDatesApiResponseProcessor.java
> +        String payload = exchange.getIn().getBody(String.class);
We have method in JsonUtil to handle non-ASCII characters but in this case I don't think it's necessary as they really shouldn't end up in this form and I'm fine with the job failing in that case. So just an FYI for future jobs.

2024-11-04 02:57 UTC, npham49 commented
Hi @weskubo-cgi, I've finished the items you commented on, and requested another review, please have the following in your application.properties:
```java

pcd-fiscal-year-reporting-dates-dir=

pcd.fiscal.year.reporting.dates.username=
pcd.fiscal.year.reporting.dates.password=
```

2024-11-04 19:03 UTC, weskubo-cgi approved these changes

2024-11-04 19:08 UTC, merged